services:
  - type: web
    name: adsync-mini
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: adsync-db
          property: connectionString

databases:
  - name: adsync-db
    plan: free
